# Generated by Django 6.0.4 on 2026-04-27 00:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.CharField(default='demo-org', max_length=120)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('article_text', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('NEW', 'New'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('assignee', models.CharField(blank=True, default='', max_length=120)),
                ('severity', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_id', models.CharField(default='demo-org', max_length=120)),
                ('event_type', models.CharField(max_length=40)),
                ('old_value', models.CharField(blank=True, default='', max_length=200)),
                ('new_value', models.CharField(blank=True, default='', max_length=200)),
                ('actor', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='analysisjob',
            new_name='platformapp_status_e5cf01_idx',
            old_name='platformapp__status_09b072_idx',
        ),
        migrations.RenameIndex(
            model_name='analysisjob',
            new_name='platformapp_org_id_4b9925_idx',
            old_name='platformapp__org_id_9f8516_idx',
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['org_id', 'updated_at'], name='platformapp_org_id_77fae3_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['org_id', 'state'], name='platformapp_org_id_6ef585_idx'),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='platformapp.case'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['case', 'created_at'], name='platformapp_case_id_d7ee89_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['org_id', 'created_at'], name='platformapp_org_id_c960d0_idx'),
        ),
    ]
