# Generated by Cursor on 2026-05-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("platformapp", "0002_case_caseevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSSFeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("url", models.URLField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("org_id", models.CharField(default="demo-org", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScoredArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("org_id", models.CharField(default="demo-org", max_length=120)),
                ("source_id", models.CharField(max_length=700)),
                ("url", models.URLField(blank=True, default="", max_length=1000)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("summary", models.TextField(blank=True, default="")),
                ("content", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("scored_at", models.DateTimeField(blank=True, null=True)),
                ("backend", models.CharField(default="classical", max_length=32)),
                (
                    "prediction",
                    models.CharField(
                        choices=[
                            ("likely_reliable", "Likely reliable"),
                            ("uncertain", "Uncertain"),
                            ("review_recommended", "Review recommended"),
                            ("model_unavailable", "Model unavailable"),
                            ("failed", "Failed"),
                        ],
                        default="uncertain",
                        max_length=32,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("flagged_for_review", models.BooleanField(default=False)),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="platformapp.rssfeed",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-ingested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="rssfeed",
            index=models.Index(fields=["is_active", "updated_at"], name="platformapp_is_acti_833f48_idx"),
        ),
        migrations.AddIndex(
            model_name="rssfeed",
            index=models.Index(fields=["org_id", "is_active"], name="platformapp_org_id_33ef56_idx"),
        ),
        migrations.AddConstraint(
            model_name="scoredarticle",
            constraint=models.UniqueConstraint(fields=("feed", "source_id"), name="uniq_feed_source_article"),
        ),
        migrations.AddIndex(
            model_name="scoredarticle",
            index=models.Index(
                fields=["org_id", "flagged_for_review", "scored_at"],
                name="platformapp_org_id_95a2ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scoredarticle",
            index=models.Index(fields=["feed", "published_at"], name="platformapp_feed_id_137c0b_idx"),
        ),
        migrations.AddIndex(
            model_name="scoredarticle",
            index=models.Index(fields=["prediction", "confidence"], name="platformapp_predict_3b0140_idx"),
        ),
    ]
